#!/bin/bash

set -e

ONBOARD_USER=onboard
ONBOARD_GROUP=$ONBOARD_USER
ONBOARD_ROOT=/home/$ONBOARD_USER/onboard
ONBOARD_GIT="https://github.com/vemarsas/onboard.git"


apt-get update
apt-get -y upgrade
apt-get -y install sudo git-core openssh-server curl vim-nox mc

install_conffiles() {
	cd $ONBOARD_ROOT
	cd doc/sysadm/examples
	install -bvC -m 440 etc/sudoers			/etc/
}

adduser --system --shell /bin/bash --group $ONBOARD_USER && \
	    echo "$ONBOARD_USER:$ONBOARD_USER" | chpasswd

su - $ONBOARD_USER -c "
if [ -d onboard ]; then
	cd onboard
	git remote set-url origin $ONBOARD_GIT
	git pull --ff-only origin margay || true
else
	git clone -b margay $ONBOARD_GIT
fi
"

install_conffiles # including sudoers

cd $ONBOARD_ROOT

bash etc/scripts/platform/debian/setup.sh $ONBOARD_ROOT $ONBOARD_USER

bash modules/openvpn/etc/scripts/platform/debian/setup.sh $ONBOARD_ROOT $ONBOARD_USER

bash modules/ap/etc/scripts/platform/debian/setup.sh $ONBOARD_ROOT $ONBOARD_USER
