#!/bin/bash

set -e

ONBOARD_USER=onboard
ONBOARD_GROUP=$ONBOARD_USER
ONBOARD_ROOT=/home/$ONBOARD_USER/onboard
ONBOARD_GIT="https://github.com/vemarsas/onboard.git"

cd $ONBOARD_ROOT

bash modules/radius-admin/etc/scripts/platform/debian/setup.sh $ONBOARD_ROOT $ONBOARD_USER
